# Generated by Django 3.2.7 on 2021-09-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_commission', models.DecimalField(decimal_places=2, help_text='판매 수수료(%)', max_digits=5)),
                ('start_date', models.DateField(help_text='계약 시작날짜', null=True)),
                ('end_date', models.DateField(help_text='계약 종료날짜', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='음식점 가게명', max_length=128)),
                ('tel_num', models.CharField(help_text='음식점 연락처', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_type', models.CharField(choices=[('food', '배달음식'), ('grocery', '식료품/가공식품'), ('pet_food', '반려동물음식')], help_text='상점 유형', max_length=32)),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
