# Generated by Django 3.2.7 on 2021-09-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='상품명', max_length=128)),
                ('price', models.IntegerField(help_text='상품 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.CharField(choices=[('grocery', '식료품'), ('furniture', '가구'), ('books', '책'), ('food', '음식')], max_length=32)),
            ],
            options={
                'db_table': 'product',
                'ordering': ('-created_at',),
            },
        ),
    ]
