default_context:
  project_name: 'hello_fastapi'
  project_slug: 'hello_fastapi'
  domain_main: 'hello-fastapi.com'
  domain_staging: 'stag.hello-fastapi.com'
  docker_swarm_stack_name_main: 'hello-fastapi-com'
  docker_swarm_stack_name_staging: 'stag-hello-fastapi-com'
  secret_key: 'changethis'
  first_superuser: 'root'
  first_superuser_password: '1234'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.hello-fastapi.com", "https://stag.hello-fastapi.com", "https://hello-fastapi.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@hello-fastapi.com'
  postgres_password: '1234'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: '1234'
  traefik_constraint_tag: 'hello-fastapi.com'
  traefik_constraint_tag_staging: 'stag.hello-fastapi.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:1234'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
